version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=bookmyspace
      - POSTGRES_USER=bookmyspace
      - POSTGRES_PASSWORD=bookmyspace